apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s7olxz83o-nodejs
  janus-idp.io/tekton: s7olxz83o-nodejs
  backstage.io/kubernetes-id: s7olxz83o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s7olxz83o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
